# Generated by Django 5.2 on 2025-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_verifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillverification',
            name='code_analysis',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='skillverification',
            name='code_skills',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddIndex(
            model_name='skillverification',
            index=models.Index(fields=['github_username'], name='skill_verif_github__ddda41_idx'),
        ),
        migrations.AddIndex(
            model_name='skillverification',
            index=models.Index(fields=['hash_value'], name='skill_verif_hash_va_91ad1e_idx'),
        ),
    ]
